// Code generated by DevUp technologies, 11/12/2023 17:29:00
namespace InventoryBlzUi.Pagination
{
    public class ManageSorting_Product
    {
        IDictionary<string, bool> GridColumns;

        public ManageSorting_Product()
        {
            GridColumns = new Dictionary<string, bool>()
			{
											{"Id", false},
											{"Name", false},
											{"CategoryId", false},
											{"NetPrice", false},
											{"SalesPrice", false},
											{"StockQuantity", false},
											{"ProductionDate", false},
											{"Status", false},

			};
        }

        public bool GetColumnStatus(string columnName)
        {
            try
            {
                return GridColumns[columnName];
            }
            catch (Exception ex)
            {
                System.Diagnostics.Trace.WriteLine(ex.ToString());
                return false;
            }
        }

        public void UpdateColumnStatus(string columnName, bool status)
        {
            try
            {
                GridColumns[columnName] = status;
            }
            catch (Exception ex)
            {
                System.Diagnostics.Trace.WriteLine(ex.ToString());
            }
        }
    }
}

